webshare:
  base_user: "USERNAME"
  password: "PASSWORD"
  host: "p.webshare.io"
  port: 80
  first_profile: 1
  max_profile: 25


pool:
  max_profile_switches_per_request: 6
  lease_timeout_seconds: 5.0
  base_sleep_seconds: 1.0
  jitter_seconds: 0.35


youtube:
  default_languages: ["bgn", "bg"]
  request_timeout_seconds: 10

llm:
  system_prompt: Ти си полезен асистент. Отговаряй на български. Бъди кратък и точен.

  model_dir: "C:/models/bggpt-2.6b"
  model_pattern: "*Q4_K_M*.gguf"


  n_ctx: 2048
  n_threads: 2
  n_gpu_layers: -1


  default_repeat_penalty: 1.1
  default_stop:
    - "</s>"
    - "### Instruction:"
    - "### Response:"